Remove hardcoded dict types and versions
lifecycle-project/ds-upload pull request #113
Opened 2022-11-25 13:37 UTC by tommydeboer

Makes the retrieval and usage of dictionary types and versions generic, so no code changes are needed when a new dictionary (version) is introduced

2022-12-16 11:36 UTC, erikzwart commented on R/login.R
> +#'   server = "https://armadillo.dev.molgenis.org"
storage is removed, this is compatible with armadillo 2?

2022-12-16 11:37 UTC, erikzwart requested changes
Is R/login.R with your changes compatible with armadillo 2?

2023-01-12 10:31 UTC, tommydeboer commented
Still needs to be tested on a live Armadillo 3.  Please wait until after the workshops end of January before merging this PR!

2023-02-02 14:04 UTC, tommydeboer commented on DESCRIPTION
> +  MolgenisArmadillo (< 2.0.0),
@erikzwart @marikaris When doing the major dsUpload release, make sure to replace these two lines with:

```MolgenisArmadillo (>= 2.0.0),```

2023-02-10 12:24 UTC, erikzwart requested changes
Used the [demo](https://github.com/lifecycle-project/ds-upload/blob/master/inst/examples/data/demo/armadillo/02_armadillo_login-upload.r) set to test, got the following error:
![image](https://user-images.githubusercontent.com/4077085/218091469-2b7ee0c8-e449-4f33-b85c-c6a12f3b97c9.png)

Zie session info (dsUpload 4.7.0):
![image](https://user-images.githubusercontent.com/4077085/218091757-8873f446-fb2f-4326-bc45-ff0f13066e0d.png)

2023-02-13 08:11 UTC, erikzwart commented
![](https://github.trello.services/images/mini-trello-icon.png) [dsUpload generiek maken dictionaries](https://trello.com/c/opzCGXZo/989-dsupload-generiek-maken-dictionaries)

2023-02-14 12:23 UTC, tommydeboer commented
Replaced by #117

2023-02-17 12:14 UTC, erikzwart commented
Closing: replaced by #117

2023-02-17 12:14 UTC, closed without merging